export const MAIN_TITLE = "TODO LIST";
export const ADD_BUTTON = "ADD +";
export const SEARCH_PLACEHOLDER = "Search by name";
export const POPUP_TITLE_CREATE = "Add new note";
export const POPUP_BUTTON_TITLE = "+";
export const FILTER_DATE_OLD_FIRST = 'Old first'
export const FILTER_DATE_NEW_FIRST = 'New first'
export const FILTER_FINISHED_FIRST = 'Show finished'
export const FILTER_UNFINISHED_FIRST = 'Show unfinished'
export const FILTER_ALL = 'Show all'
